# The path for the folder where all reslts will be stored
workingPath: 'D:/05 MeSHToUMLS/MeSH_extension/'
# The path to the folder with the CSV files from the excecution of the MeSH_Harvesting project
csvPath: 'D:/05 MeSHToUMLS/MeSH_extension/2005_2020_results/'
# The last year to consider in the analysis
lastYear: 2020
# The first year to consider in the analysis
firstYear: 2005
# The character for joining/splitting serialized information
splitChar: '~'
